DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    nickname VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL,
    signed_up_at TIMESTAMP NOT NULL,
    password VARCHAR(250) NOT NULL
);